branch-defaults:
  master:
    environment: null
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: Udagram-imagefilter
  branch: test
  default_ec2_keyname: aws-eb
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: image-filter
  sc: git
  workspace_type: Application
